{% set name = "ansys-tools-path" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ansys_tools_path-{{ version }}.tar.gz
  sha256: 96663cd13436e20f2ab2347aa6c487890962319c80bebc181419c957c19a8de0

build:
  entry_points:
    - save-ansys-path = ansys.tools.path.save:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }},<4.0
    - platformdirs >=3.6.0
    - click >=8.1.3

test:
  imports:
    - ansys.tools.path
  commands:
    - pip check
    - save-ansys-path --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://path.tools.docs.pyansys.com/
  summary: Library to locate Ansys products in a local machine.
  dev_url: https://github.com/ansys/ansys-tools-path
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MaxJPRey
    - jorgepiloto
    - SMoraisAnsys
    - RobPasMue
