{% set name = "ansys-tools-path" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ansys_tools_path-{{ version }}.tar.gz
  sha256: a6a3a35b2700905319347c785b59a7ac12e6f60148b3b516ec09546463fe9c8f

build:
  entry_points:
    - save-ansys-path = ansys.tools.path.save:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8,<4.0
    - platformdirs >=3.6.0
    - click >=8.1.3

test:
  imports:
    - ansys.tools.path
  commands:
    - pip check
    - save-ansys-path --help
  requires:
    - pip

about:
  home: https://path.tools.docs.pyansys.com/
  summary: Library to locate Ansys products in a local machine.
  dev_url: https://github.com/ansys/ansys-tools-path
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MaxJPRey
    - jorgepiloto
    - SMoraisAnsys
    - RobPasMue
